version: '3.8'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    restart: always
    depends_on:
      - nginx 

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./build:/usr/share/nginx/html
    restart: always
